# Generated by Django 4.2.27 on 2025-12-12 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.date(2025, 12, 11), verbose_name='Data Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(verbose_name='Previsão devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('E', 'Emprestado'), ('D', 'Devolvido')], default='E', max_length=1),
        ),
    ]
