# Generated by Django 4.2.27 on 2025-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Emprestado', 'Emprestado'), ('Devolvido', 'Devolvido')], default='Emprestado', max_length=10),
        ),
    ]
