# Generated by Django 4.2.27 on 2025-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, verbose_name='Data Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('E', 'Emprestado'), ('D', 'Devolvido')], default='E', max_length=1),
        ),
    ]
